### PR TITLE
Fix scalastyleConfig in multi-project builds

### LINKED ISSUE #42: Setting scalastyleConfig doesnt work
To get Scalastyle SBT to work with scalastyle IntelliJ idea plugin, the file needs to be in `./idea` or `./project` folders and the config file needs to be called  `scalastyle_config.xml` (not `scalastyle-config.xml`). 

This is really silly as you would think everything would be consistent. When trying to set sbt to use the `scalastyle_config.xml` in the project folder in a multi module project it doesnt work! 

`scalastyleConfig := file("project/scalastyle_config.xml")`

in sbt;

```
> show scalastyleConfig
[info] reports/*:scalastyleConfig
[info]  scalastyle-config.xml
[info] report-api-common/*:scalastyleConfig
[info]  scalastyle-config.xml
[info] report-sparkjobs/*:scalastyleConfig
[info]  scalastyle-config.xml
[info] etl/*:scalastyleConfig
[info]  scalastyle-config.xml
[info] common/*:scalastyleConfig
[info]  scalastyle-config.xml
[info] root-project/*:scalastyleConfig
[info]  project/scalastyle_config.xml
```

This is beyond frustrating.

### LINKED ISSUE #44: Setting (scalastyleConfig in Test) inside an AutoPlugin doesn't work
I'm trying to extract shared plugins and settings into a common set of AutoPlugins. Here's the plugin for Scalastyle:

``` scala
package com.jawshooah.sbt

import sbt._
import sbt.Keys._
import sbt.plugins.JvmPlugin

import org.scalastyle.sbt.ScalastylePlugin
import org.scalastyle.sbt.ScalastylePlugin._

object ScalastylePluginSettings extends AutoPlugin {
  override def requires = JvmPlugin
  override def trigger = allRequirements

  /* ScalastylePlugin is not an AutoPlugin, so we manually add its settings here */
  override def projectSettings =
    ScalastylePlugin.projectSettings ++
    baseSettings ++
    Project.inConfig(Compile)(baseSettings) ++
    Project.inConfig(Test)(baseSettings)

  lazy val baseSettings = Seq(
    (scalastyleConfig in Compile) := sbtCommonDir.value / "scalastyle-config.xml",
    (scalastyleConfig in Test) := sbtCommonDir.value / "scalastyle-test-config.xml"
  )

  lazy val sbtCommonDir = baseDirectory { _ / "project" / "sbt-common" }
}
```

`scalastyleConfig` appears to be set correctly in `Compile`:

```
> inspect compile:scalastyleConfig
[info] Setting: java.io.File = /Users/joshuahagins/dev/sandbox/sbt-common-test/project/sbt-common/scalastyle-config.xml
[info] Description:
[info]  Scalastyle configuration file
[info] Provided by:
[info]  {file:/Users/joshuahagins/dev/sandbox/sbt-common-test/}root/compile:scalastyleConfig
[info] Defined at:
[info]  (com.jawshooah.sbt.ScalastylePluginSettings) ScalastylePluginSettings.scala:22
[info] Dependencies:
[info]  compile:baseDirectory
[info] Reverse dependencies:
[info]  compile:scalastyleGenerateConfig
[info]  compile:scalastyle
[info] Delegates:
[info]  compile:scalastyleConfig
[info]  *:scalastyleConfig
[info]  {.}/compile:scalastyleConfig
[info]  {.}/*:scalastyleConfig
[info]  */compile:scalastyleConfig
[info]  */*:scalastyleConfig
[info] Related:
[info]  *:scalastyle::scalastyleConfig
[info]  test:scalastyle::scalastyleConfig
[info]  test:scalastyleConfig
[info]  compile:scalastyle::scalastyleConfig
[info]  *:scalastyleConfig
```

...but not in `Test`:

```
> inspect test:scalastyleConfig
[info] Setting: java.io.File = scalastyle-config.xml
[info] Description:
[info]  Scalastyle configuration file
[info] Provided by:
[info]  {file:/Users/joshuahagins/dev/sandbox/sbt-common-test/}root/test:scalastyleConfig
[info] Defined at:
[info]  (org.scalastyle.sbt.ScalastylePlugin) Plugin.scala:100
[info] Dependencies:
[info]  *:scalastyle::scalastyleConfig
[info] Reverse dependencies:
[info]  test:scalastyleGenerateConfig
[info]  test:scalastyle
[info] Delegates:
[info]  test:scalastyleConfig
[info]  runtime:scalastyleConfig
[info]  compile:scalastyleConfig
[info]  *:scalastyleConfig
[info]  {.}/test:scalastyleConfig
[info]  {.}/runtime:scalastyleConfig
[info]  {.}/compile:scalastyleConfig
[info]  {.}/*:scalastyleConfig
[info]  */test:scalastyleConfig
[info]  */runtime:scalastyleConfig
[info]  */compile:scalastyleConfig
[info]  */*:scalastyleConfig
[info] Related:
[info]  compile:scalastyleConfig
[info]  *:scalastyleConfig
```

If I add the line:

``` scala
(scalastyleConfig in scalastyle) := sbtCommonDir.value / "scalastyle-test-config.xml"
```

...it works. I assume this is related to the way `scalastyleConfig in Test` is [initially set](https://github.com/scalastyle/scalastyle-sbt-plugin/blob/d344ef422a833b4cbfffff7c4682c83815fd3210/src/main/scala/org/scalastyle/sbt/Plugin.scala#L100), but this is very counterintuitive, and I'm not sure if it has any other repercussions.

### PR DESCRIPTION
**Pull request by gcpagano**
This is to get the plugin to properly work with multi-projects build.
This PR should resolve #42 and resolve #44 
It's using the _auto-plugins_ feature introduced in 0.13.5, the downside is that it will only be compatible with sbt 0.13.5+

### CODE REVIEW

**Comment by mhzajac** [comment]
Will this ever be merged, or looked at? It works as best as I can tell, and fixed all of the issues I was having with my large multi-project builds.

**Comment by ayoub-benali** [comment]
What is the status if the PR ?

**Comment by matthewfarwell** [comment]
Sorry, I've been really busy. I may have some time this week or next, I'll look at it.

**Comment by marekrogala** [comment]
:+1: 
@matthewfarwell  can you take a look?

**Comment by filipesabella** [comment]
Also having problems with this.

**Comment by abhamjee** [comment]
We too really need this.

**Comment by kflorence** [comment]
Is this project dead?

**Comment by matthewfarwell** [comment]
The master of the sbt plugin is now compatible with AutoPlugin. Can you try this and see if it works with your builds, or if there are other things that need to happen? I will look on my side.

**Comment by gcpagano** [comment]
I've updated the PR, rebasing it on the current master.
The test for multi-projects build works for me.
The travis build is failing because of the before_install section currently in master, and it doesn't seem releated to this PR. Here is the error:
```$ sudo hostname "$(hostname | cut -c1-63)"

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid, and setgid executables.

If you require sudo, add 'sudo: required' to your .travis.yml

The command "sudo hostname "$(hostname | cut -c1-63)"" failed and exited with 1 during .```

**Comment by matthewfarwell** [comment]
Cool. Thanks!

**Pull request merged**
