### PR TITLE
Support specifying specific files/directories to process

### PR DESCRIPTION
**Pull request by ajsquared**
From the discussion on #37

### CODE REVIEW

**Comment by matthewfarwell** [comment]
Thanks. I'll look at this as soon as I can.

**Comment by ajsquared** [comment]
@matthewfarwell Have you had a chance to look over this yet?

**Comment by matthewfarwell** [comment]
I'm sorry, I've been a bit busy - I'll look at this later this week. Thanks.

**Comment by ajsquared** [comment]
@matthewfarwell I wanted to check in about this PR.  Have you had any time to look over it?  Thanks!

**Comment by kflorence** [comment]
How do I use this? Please update documentation.

**Pull request merged**
